// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PortfolioRealtime.FlatBuffers
{

public enum PacketType : byte
{
  NONE = 0,
  Heartbeat = 1,
  ChatMessage = 2,
};


}
